# Generated by Django 5.1.3 on 2024-12-05 16:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('rate_currency', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyHistoryBid',
            fields=[
                ('history_transaction_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('history_date', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencyData.transaction')),
            ],
            options={
                'ordering': ['transaction_name', '-history_date'],
            },
        ),
    ]
