# Generated by Django 5.1.3 on 2024-12-02 20:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('rate_currency', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyHistoryBid',
            fields=[
                ('history_transaction_name', models.CharField(blank=True, max_length=10, null=True)),
                ('history_transaction_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('history_date', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-history_date'],
            },
        ),
    ]
