# Generated by Django 5.1.3 on 2024-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistorybid',
            name='history_transaction_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currencyhistorybid',
            name='history_transaction_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
