# Generated by Django 5.1.3 on 2024-12-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyData', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyHistoryBid',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
